/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package viewer;

import java.awt.Frame;
import javax.swing.JOptionPane;
import org.hibernate.HibernateException;
import control.GerInterGrafica;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.border.BevelBorder;
import model.Avatar;
import model.Usuario;


public class DlgCadUser extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DlgCadUser.class.getName());

    private Usuario novoUser = null ;
    private Avatar avatar = null;
    public DlgCadUser(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCadastroUser = new javax.swing.JPanel();
        lblUserName = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        pnlAvatar = new javax.swing.JPanel();
        lblAvatar2 = new javax.swing.JLabel();
        lblAvatar1 = new javax.swing.JLabel();
        btnCadastrarUser = new javax.swing.JButton();
        btnCancelarCadUser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        pnlCadastroUser.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Cadastre-se ")));

        lblUserName.setText("Apelido");

        txtUserName.addActionListener(this::txtUserNameActionPerformed);

        lblNome.setText("Nome Completo");

        javax.swing.GroupLayout pnlCadastroUserLayout = new javax.swing.GroupLayout(pnlCadastroUser);
        pnlCadastroUser.setLayout(pnlCadastroUserLayout);
        pnlCadastroUserLayout.setHorizontalGroup(
            pnlCadastroUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroUserLayout.createSequentialGroup()
                .addGroup(pnlCadastroUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCadastroUserLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNome))
                    .addGroup(pnlCadastroUserLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblUserName)))
                .addGap(18, 18, 18)
                .addGroup(pnlCadastroUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        pnlCadastroUserLayout.setVerticalGroup(
            pnlCadastroUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCadastroUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCadastroUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserName)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlAvatar.setBorder(javax.swing.BorderFactory.createTitledBorder("Escolha seu Avatar"));

        lblAvatar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arqueiro.png"))); // NOI18N
        lblAvatar2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblAvatar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAvatar2MouseClicked(evt);
            }
        });

        lblAvatar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Guerreiro.png"))); // NOI18N
        lblAvatar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblAvatar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAvatar1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlAvatarLayout = new javax.swing.GroupLayout(pnlAvatar);
        pnlAvatar.setLayout(pnlAvatarLayout);
        pnlAvatarLayout.setHorizontalGroup(
            pnlAvatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAvatarLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(lblAvatar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAvatar2)
                .addGap(89, 89, 89))
        );
        pnlAvatarLayout.setVerticalGroup(
            pnlAvatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAvatarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAvatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAvatar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvatar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        btnCadastrarUser.setText("Cadastrar");
        btnCadastrarUser.addActionListener(this::btnCadastrarUserActionPerformed);

        btnCancelarCadUser.setText("Cancelar");
        btnCancelarCadUser.addActionListener(this::btnCancelarCadUserActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCadastrarUser)
                        .addGap(70, 70, 70)
                        .addComponent(btnCancelarCadUser)
                        .addGap(92, 92, 92))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlAvatar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pnlCadastroUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(pnlCadastroUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarUser)
                    .addComponent(btnCancelarCadUser)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void btnCancelarCadUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCadUserActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarCadUserActionPerformed

    private void btnCadastrarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarUserActionPerformed
       String user = txtUserName.getText().trim();
       String nome = txtNome.getText().trim();
       if (nome.isEmpty() || user.isEmpty()) {
           JOptionPane.showMessageDialog(rootPane, "Preencha Nome Completo e Apelido.");
           return;
       }
       if (avatar == null) {
           JOptionPane.showMessageDialog(rootPane, "Escolha um avatar.");
           return;
       }
        if(novoUser == null){
            novoUser = new Usuario(nome,user,avatar);
        }
        try {
            GerInterGrafica.getMyInstance().getGerenciadorDominio().inserir(novoUser);
            MainFrame main = (MainFrame) this.getOwner();
            main.carregarUsuariosCadastrados();
            JOptionPane.showMessageDialog(rootPane, novoUser + " cadastrado.");
            dispose();
        } catch (HibernateException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao cadastrar usuario: " + ex.getMessage());
        }

    }//GEN-LAST:event_btnCadastrarUserActionPerformed

    private void lblAvatar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAvatar1MouseClicked
        this.selecionarAvatar(lblAvatar1);
        if (avatar != Avatar.GUERREIRO){
            avatar = Avatar.GUERREIRO;
        }
    }//GEN-LAST:event_lblAvatar1MouseClicked

    private void lblAvatar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAvatar2MouseClicked
        this.selecionarAvatar(lblAvatar2);
        if (avatar != Avatar.ARQUEIRO){
            avatar = Avatar.ARQUEIRO;
        }
    }//GEN-LAST:event_lblAvatar2MouseClicked

    private void selecionarAvatar(JLabel labelSelecionado) {
        javax.swing.border.Border bordaPadrao = BorderFactory.createBevelBorder(BevelBorder.RAISED);

        lblAvatar1.setBorder(bordaPadrao);
        lblAvatar2.setBorder(bordaPadrao);

        labelSelecionado.setBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED));

}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarUser;
    private javax.swing.JButton btnCancelarCadUser;
    private javax.swing.JLabel lblAvatar1;
    private javax.swing.JLabel lblAvatar2;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPanel pnlAvatar;
    private javax.swing.JPanel pnlCadastroUser;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
