/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package viewer;

import control.GerInterGrafica;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Jogo;
import model.Usuario;
import org.hibernate.HibernateException;


public class UserFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserFrame.class.getName());

    /**
     * Creates new form UserFrame
     */
    private Usuario usuario;

    public UserFrame() {
        initComponents();
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
        carregarTabelaJogos();
    }

    private void carregarTabelaJogos() {
        DefaultTableModel model = (DefaultTableModel) tblJogosUser.getModel();
        model.setRowCount(0);

        if (usuario == null) {
            return;
        }

        try {
            List<Jogo> jogos = GerInterGrafica.getMyInstance()
                    .getGerenciadorDominio()
                    .listarJogosDoUsuario(usuario.getIdUsuario());

            for (Jogo j : jogos) {
                String plataforma = j.getPlataforma() != null ? j.getPlataforma().getNome() : "";
                String tempoConclusao = j.getTempoJogo() != null ? j.getTempoJogo() : "";
                String dificuldade = j.getDificuldade() != null ? j.getDificuldade() : "";
                String avaliacao = j.getRegistroZerado() != null ? String.valueOf(j.getRegistroZerado().getNotaPessoal()) : "";
                model.addRow(new Object[]{j.getTitulo(), plataforma, tempoConclusao, dificuldade, avaliacao});
            }
        } catch (HibernateException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao carregar jogos do usuário: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGameboxUser = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblJogosUser = new javax.swing.JTable();
        btnAdicionarJogo = new javax.swing.JButton();
        txtBuscarJogo = new javax.swing.JTextField();
        lblBuscar = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblGameboxUser.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblGameboxUser.setText("Game Box");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabela de Jogos"));

        tblJogosUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titulo", "Plataforma", "Tempo de Conclusão", "Dificuldade", "Avaliação"
            }
        ));
        jScrollPane1.setViewportView(tblJogosUser);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        btnAdicionarJogo.setText("Adicionar jogo");
        btnAdicionarJogo.addActionListener(this::btnAdicionarJogoActionPerformed);

        txtBuscarJogo.addActionListener(this::txtBuscarJogoActionPerformed);

        lblBuscar.setText("Buscar");

        jButton1.setText("Sair");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblGameboxUser, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(363, 363, 363)
                                .addComponent(lblBuscar)
                                .addGap(55, 55, 55))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBuscarJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(btnAdicionarJogo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblGameboxUser, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscarJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionarJogo)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarJogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarJogoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        GerInterGrafica.getMyInstance().fecharUser();
        GerInterGrafica.getMyInstance().abrirPrincipal();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAdicionarJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarJogoActionPerformed
        GerInterGrafica.getMyInstance().abrirCadJogo();
        // o dialog é modal; ao voltar, recarrega tabela
        carregarTabelaJogos();
    }//GEN-LAST:event_btnAdicionarJogoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarJogo;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblGameboxUser;
    private javax.swing.JTable tblJogosUser;
    private javax.swing.JTextField txtBuscarJogo;
    // End of variables declaration//GEN-END:variables
}
